"""
Alert service for sending notifications
"""

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from typing import List, Dict
from app.core.config import settings


class AlertService:
    """Service for sending alerts via email/SMS"""
    
    def __init__(self):
        self.sendgrid_client = None
        if settings.SENDGRID_API_KEY:
            self.sendgrid_client = SendGridAPIClient(settings.SENDGRID_API_KEY)
    
    async def send_outbreak_alert(
        self,
        recipients: List[str],
        alert_data: Dict
    ) -> Dict:
        """
        Send outbreak alert via email
        
        Args:
            recipients: List of email addresses
            alert_data: Alert information
        
        Returns:
            Dict with delivery status
        """
        
        if not self.sendgrid_client:
            return {"status": "skipped", "reason": "SendGrid not configured"}
        
        html_content = self._generate_alert_email(alert_data)
        
        message = Mail(
            from_email=settings.SENDGRID_FROM_EMAIL,
            to_emails=recipients,
            subject=f"🚨 {alert_data['severity'].upper()} - {alert_data['title']}",
            html_content=html_content
        )
        
        try:
            response = self.sendgrid_client.send(message)
            return {
                "status": "sent",
                "status_code": response.status_code,
                "recipients_count": len(recipients)
            }
        except Exception as e:
            return {
                "status": "failed",
                "error": str(e)
            }
    
    def _generate_alert_email(self, alert_data: Dict) -> str:
        """Generate HTML email content"""
        
        severity_colors = {
            "critical": "#DC2626",
            "warning": "#F59E0B",
            "info": "#3B82F6"
        }
        
        color = severity_colors.get(alert_data.get("severity", "info"), "#6B7280")
        
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                .header {{ background: {color}; color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
                .content {{ background: #f9fafb; padding: 20px; }}
                .alert-box {{ background: white; padding: 15px; margin: 10px 0; border-left: 4px solid {color}; }}
                .button {{ background: {color}; color: white; padding: 12px 24px; text-decoration: none; 
                          border-radius: 6px; display: inline-block; margin-top: 15px; }}
                .footer {{ text-align: center; margin-top: 20px; color: #6B7280; font-size: 12px; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🚨 Disease Outbreak Alert</h1>
                </div>
                <div class="content">
                    <div class="alert-box">
                        <h2>{alert_data.get('title', 'Health Alert')}</h2>
                        <p>{alert_data.get('message', '')}</p>
                        
                        <p><strong>Zone:</strong> {alert_data.get('zone_name', 'N/A')}</p>
                        <p><strong>Risk Level:</strong> {alert_data.get('risk_level', 'N/A').upper()}</p>
                        <p><strong>Disease:</strong> {alert_data.get('disease', 'N/A')}</p>
                        <p><strong>Predicted Cases:</strong> {alert_data.get('predicted_cases', 'N/A')}</p>
                        <p><strong>Time Frame:</strong> {alert_data.get('timeframe', 'Next 7 days')}</p>
                        
                        <h3>Recommended Actions:</h3>
                        <ul>
                            <li>Enhanced surveillance in the affected area</li>
                            <li>Prepare additional healthcare capacity</li>
                            <li>Initiate preventive measures</li>
                            <li>Inform local health departments</li>
                        </ul>
                        
                        <a href="{alert_data.get('dashboard_link', '#')}" class="button">
                            View Full Details on Dashboard
                        </a>
                    </div>
                </div>
                <div class="footer">
                    <p>This alert was generated by SymptoMap Disease Surveillance System</p>
                    <p>For support, contact: support@symptomap.com</p>
                </div>
            </div>
        </body>
        </html>
        """
        
        return html
