"""
PDF Export Service for chatbot conversations
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from datetime import datetime, timezone
import io


class PDFExportService:
    """Generate PDF reports from chatbot conversations"""
    
    def generate_conversation_pdf(self, conversation_data: dict) -> bytes:
        """
        Generate PDF report from conversation
        
        Args:
            conversation_data: Complete conversation with assessment
        
        Returns:
            PDF file as bytes
        """
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#10B981'),
            spaceAfter=30
        )
        story.append(Paragraph("AI Health Assistant Report", title_style))
        story.append(Spacer(1, 0.2*inch))
        
        # Metadata
        story.append(Paragraph(f"<b>Session ID:</b> {conversation_data.get('session_id', 'N/A')}", styles['Normal']))
        story.append(Paragraph(f"<b>Date:</b> {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", styles['Normal']))
        story.append(Spacer(1, 0.3*inch))
        
        # Disclaimer
        disclaimer_style = ParagraphStyle(
            'Disclaimer',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.red,
            leftIndent=20,
            rightIndent=20,
            spaceBefore=10,
            spaceAfter=10
        )
        disclaimer = "⚠️ <b>MEDICAL DISCLAIMER:</b> This report is generated by an AI assistant and is NOT a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or qualified health provider."
        story.append(Paragraph(disclaimer, disclaimer_style))
        story.append(Spacer(1, 0.3*inch))
        
        # SOAP Note
        if conversation_data.get('soap_note'):
            story.append(Paragraph("<b>SOAP Note</b>", styles['Heading2']))
            soap = conversation_data['soap_note']
            
            for section in ['subjective', 'objective', 'assessment', 'plan']:
                if section in soap:
                    story.append(Paragraph(f"<b>{section.upper()}</b>", styles['Heading3']))
                    story.append(Paragraph(soap[section], styles['Normal']))
                    story.append(Spacer(1, 0.15*inch))
        
        # Assessment
        if conversation_data.get('assessment'):
            story.append(Spacer(1, 0.2*inch))
            story.append(Paragraph("<b>Assessment Summary</b>", styles['Heading2']))
            
            assessment = conversation_data['assessment']
            
            # Severity
            severity = assessment.get('severity', 'N/A').upper()
            severity_color = {
                'EMERGENCY': colors.red,
                'URGENT': colors.orange,
                'ROUTINE': colors.green
            }.get(severity, colors.gray)
            
            story.append(Paragraph(f"<b>Severity:</b> <font color='{severity_color}'>{severity}</font>", styles['Normal']))
            
            # Primary Diagnosis
            if assessment.get('primary_diagnosis'):
                diag = assessment['primary_diagnosis']
                story.append(Paragraph(
                    f"<b>Primary Diagnosis:</b> {diag.get('condition', 'N/A')} "
                    f"(Confidence: {int(diag.get('confidence', 0) * 100)}%)",
                    styles['Normal']
                ))
        
        # Recommendations
        if conversation_data.get('recommendations'):
            story.append(Spacer(1, 0.2*inch))
            story.append(Paragraph("<b>Recommendations</b>", styles['Heading2']))
            
            recs = conversation_data['recommendations']
            
            if recs.get('home_care'):
                story.append(Paragraph("<b>Home Care:</b>", styles['Normal']))
                for item in recs['home_care']:
                    story.append(Paragraph(f"• {item}", styles['Normal']))
            
            if recs.get('when_to_see_doctor'):
                story.append(Spacer(1, 0.1*inch))
                story.append(Paragraph("<b>When to See a Doctor:</b>", styles['Normal']))
                doctor_recs = recs['when_to_see_doctor']
                if doctor_recs.get('routine'):
                    for item in doctor_recs['routine']:
                        story.append(Paragraph(f"• {item}", styles['Normal']))
        
        # Build PDF
        doc.build(story)
        
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
