"""
PDF Report Generation API
Generates downloadable PDF reports for outbreak data
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from datetime import datetime, timezone, timedelta
import sqlite3
import os
from io import BytesIO

router = APIRouter(prefix="/reports", tags=["PDF Reports"])


def get_db_connection():
    """Get SQLite database connection"""
    db_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))), 'symptomap.db')
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def generate_text_report():
    """Generate a text-based report (PDF generation requires external library)"""
    
    now = datetime.now(timezone.utc)
    report_date = now.strftime("%Y-%m-%d %H:%M UTC")
    
    # Get data from SQLite
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Get outbreak stats
    cursor.execute("SELECT COUNT(*) as total FROM doctor_outbreaks")
    total_outbreaks = cursor.fetchone()['total']
    
    cursor.execute("SELECT COUNT(*) as count FROM doctor_outbreaks WHERE status = 'approved'")
    approved = cursor.fetchone()['count']
    
    cursor.execute("SELECT COUNT(*) as count FROM doctor_outbreaks WHERE status = 'pending' OR status IS NULL")
    pending = cursor.fetchone()['count']
    
    cursor.execute("SELECT COUNT(*) as count FROM doctor_outbreaks WHERE severity = 'severe'")
    severe = cursor.fetchone()['count']
    
    cursor.execute("SELECT SUM(patient_count) as total FROM doctor_outbreaks WHERE status = 'approved'")
    row = cursor.fetchone()
    total_cases = row['total'] if row['total'] else 0
    
    # Get by disease
    cursor.execute("""
        SELECT disease_type, COUNT(*) as count, SUM(patient_count) as cases
        FROM doctor_outbreaks 
        WHERE status = 'approved'
        GROUP BY disease_type
        ORDER BY count DESC
    """)
    disease_data = cursor.fetchall()
    
    # Get by state
    cursor.execute("""
        SELECT state, COUNT(*) as count, SUM(patient_count) as cases
        FROM doctor_outbreaks 
        WHERE status = 'approved' AND state IS NOT NULL
        GROUP BY state
        ORDER BY count DESC
    """)
    state_data = cursor.fetchall()
    
    conn.close()
    
    # Build report text
    report = f"""
================================================================================
                    SYMPTOMAP OUTBREAK INTELLIGENCE REPORT
================================================================================

Report Generated: {report_date}
Report Type: Doctor Submission Summary

================================================================================
                              EXECUTIVE SUMMARY
================================================================================

Total Submissions:     {total_outbreaks}
Approved Outbreaks:    {approved}
Pending Review:        {pending}
Critical (Severe):     {severe}
Total Cases Reported:  {total_cases}

================================================================================
                            OUTBREAK BY DISEASE TYPE
================================================================================

{"Disease Type":<25} {"Outbreaks":<12} {"Cases":<12}
{"-"*49}
"""
    
    for row in disease_data:
        report += f"{row['disease_type']:<25} {row['count']:<12} {row['cases'] or 0:<12}\n"
    
    report += f"""
================================================================================
                            OUTBREAK BY STATE/REGION
================================================================================

{"State":<25} {"Outbreaks":<12} {"Cases":<12}
{"-"*49}
"""
    
    for row in state_data:
        report += f"{row['state']:<25} {row['count']:<12} {row['cases'] or 0:<12}\n"
    
    report += f"""
================================================================================
                              SYSTEM STATUS
================================================================================

Dashboard Status:      OPERATIONAL
Data Sync:             REAL-TIME
Last Updated:          {report_date}

================================================================================
                              CLASSIFICATION
================================================================================

This report contains aggregated outbreak intelligence data.
For official use by authorized personnel only.

Generated by SymptoMap Disease Outbreak Tracking System
https://github.com/Rajkaran-122/Symptomap_2_python

================================================================================
"""
    
    return report


@router.get("/download/summary")
async def download_summary_report():
    """
    Download a summary report as a text file
    
    Returns a downloadable text report with outbreak statistics
    """
    try:
        report_content = generate_text_report()
        
        # Generate filename
        filename = f"symptomap_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        
        return Response(
            content=report_content,
            media_type="text/plain",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"'
            }
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating report: {str(e)}")


@router.get("/data/summary")
async def get_report_data():
    """
    Get report data as JSON for frontend rendering
    """
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        # Get outbreak stats
        cursor.execute("SELECT COUNT(*) as total FROM doctor_outbreaks")
        total_outbreaks = cursor.fetchone()['total']
        
        cursor.execute("SELECT COUNT(*) as count FROM doctor_outbreaks WHERE status = 'approved'")
        approved = cursor.fetchone()['count']
        
        cursor.execute("SELECT COUNT(*) as count FROM doctor_outbreaks WHERE status = 'pending' OR status IS NULL")
        pending = cursor.fetchone()['count']
        
        cursor.execute("SELECT COUNT(*) as count FROM doctor_outbreaks WHERE severity = 'severe'")
        severe = cursor.fetchone()['count']
        
        cursor.execute("SELECT SUM(patient_count) as total FROM doctor_outbreaks WHERE status = 'approved'")
        row = cursor.fetchone()
        total_cases = row['total'] if row['total'] else 0
        
        # Get by disease
        cursor.execute("""
            SELECT disease_type, COUNT(*) as count, SUM(patient_count) as cases
            FROM doctor_outbreaks 
            WHERE status = 'approved'
            GROUP BY disease_type
            ORDER BY count DESC
        """)
        disease_data = [{"disease": r['disease_type'], "outbreaks": r['count'], "cases": r['cases'] or 0} for r in cursor.fetchall()]
        
        # Get by state
        cursor.execute("""
            SELECT state, COUNT(*) as count, SUM(patient_count) as cases
            FROM doctor_outbreaks 
            WHERE status = 'approved' AND state IS NOT NULL
            GROUP BY state
            ORDER BY count DESC
        """)
        state_data = [{"state": r['state'], "outbreaks": r['count'], "cases": r['cases'] or 0} for r in cursor.fetchall()]
        
        conn.close()
        
        return {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "summary": {
                "total_submissions": total_outbreaks,
                "approved": approved,
                "pending": pending,
                "severe": severe,
                "total_cases": total_cases
            },
            "by_disease": disease_data,
            "by_state": state_data
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching report data: {str(e)}")
