"""Initial schema

Revision ID: b1de669813f4
Revises: 
Create Date: 2026-02-09 14:51:09.050386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1de669813f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('notify_outbreaks', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('notify_approvals', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('notify_alerts', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('notify_reports', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('subscribed_at', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
